
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.froi.arbolactivacion.gramaticas;

/** CUP generated class containing symbol constants. */
public class GramaticaParserSym {
  /* terminals */
  public static final int PUNTOS = 8;
  public static final int INTEGER = 14;
  public static final int PROGRAMA = 2;
  public static final int PUNTO_COMA = 9;
  public static final int PARAMS = 5;
  public static final int EOF = 0;
  public static final int IGUAL = 10;
  public static final int error = 1;
  public static final int PROCEDIMIENTO = 3;
  public static final int PARC = 12;
  public static final int ALFANUMERICO = 13;
  public static final int PARA = 11;
  public static final int END = 7;
  public static final int BEGIN = 6;
  public static final int PARAM = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PROGRAMA",
  "PROCEDIMIENTO",
  "PARAM",
  "PARAMS",
  "BEGIN",
  "END",
  "PUNTOS",
  "PUNTO_COMA",
  "IGUAL",
  "PARA",
  "PARC",
  "ALFANUMERICO",
  "INTEGER"
  };
}

